// SPDX-License-Identifier: GPL-3.0-only
package web

import "strings"

// English region names come from the platform's Unicode CLDR locale data.
var countryCodes = map[string]string{
	"ac":                                     "AC",
	"ad":                                     "AD",
	"ae":                                     "AE",
	"af":                                     "AF",
	"afghanistan":                            "AF",
	"ag":                                     "AG",
	"ai":                                     "AI",
	"al":                                     "AL",
	"åland islands":                          "AX",
	"albania":                                "AL",
	"algeria":                                "DZ",
	"am":                                     "AM",
	"american samoa":                         "AS",
	"an":                                     "CW",
	"andorra":                                "AD",
	"angola":                                 "AO",
	"anguilla":                               "AI",
	"antarctica":                             "AQ",
	"antigua & barbuda":                      "AG",
	"ao":                                     "AO",
	"aq":                                     "AQ",
	"ar":                                     "AR",
	"argentina":                              "AR",
	"armenia":                                "AM",
	"aruba":                                  "AW",
	"as":                                     "AS",
	"ascension island":                       "AC",
	"at":                                     "AT",
	"au":                                     "AU",
	"australia":                              "AU",
	"austria":                                "AT",
	"aw":                                     "AW",
	"ax":                                     "AX",
	"az":                                     "AZ",
	"azerbaijan":                             "AZ",
	"ba":                                     "BA",
	"bahamas":                                "BS",
	"bahrain":                                "BH",
	"bangladesh":                             "BD",
	"barbados":                               "BB",
	"bb":                                     "BB",
	"bd":                                     "BD",
	"be":                                     "BE",
	"belarus":                                "BY",
	"belgium":                                "BE",
	"belize":                                 "BZ",
	"benin":                                  "BJ",
	"bermuda":                                "BM",
	"bf":                                     "BF",
	"bg":                                     "BG",
	"bh":                                     "BH",
	"bhutan":                                 "BT",
	"bi":                                     "BI",
	"bj":                                     "BJ",
	"bl":                                     "BL",
	"bm":                                     "BM",
	"bn":                                     "BN",
	"bo":                                     "BO",
	"bolivia":                                "BO",
	"bolivia, plurinational state of":        "BO",
	"bosnia & herzegovina":                   "BA",
	"botswana":                               "BW",
	"bouvet island":                          "BV",
	"bq":                                     "BQ",
	"br":                                     "BR",
	"brazil":                                 "BR",
	"british indian ocean territory":         "IO",
	"british virgin islands":                 "VG",
	"brunei":                                 "BN",
	"bs":                                     "BS",
	"bt":                                     "BT",
	"bu":                                     "MM",
	"bulgaria":                               "BG",
	"burkina faso":                           "BF",
	"burundi":                                "BI",
	"bv":                                     "BV",
	"bw":                                     "BW",
	"by":                                     "BY",
	"bz":                                     "BZ",
	"ca":                                     "CA",
	"cambodia":                               "KH",
	"cameroon":                               "CM",
	"canada":                                 "CA",
	"canary islands":                         "IC",
	"cape verde":                             "CV",
	"caribbean netherlands":                  "BQ",
	"cayman islands":                         "KY",
	"cc":                                     "CC",
	"cd":                                     "CD",
	"central african republic":               "CF",
	"ceuta & melilla":                        "EA",
	"cf":                                     "CF",
	"cg":                                     "CG",
	"ch":                                     "CH",
	"chad":                                   "TD",
	"chile":                                  "CL",
	"china":                                  "CN",
	"christmas island":                       "CX",
	"ci":                                     "CI",
	"ck":                                     "CK",
	"cl":                                     "CL",
	"clipperton island":                      "CP",
	"cm":                                     "CM",
	"cn":                                     "CN",
	"co":                                     "CO",
	"cocos (keeling) islands":                "CC",
	"colombia":                               "CO",
	"comoros":                                "KM",
	"congo - brazzaville":                    "CG",
	"congo - kinshasa":                       "CD",
	"cook islands":                           "CK",
	"costa rica":                             "CR",
	"côte d’ivoire":                          "CI",
	"cp":                                     "CP",
	"cq":                                     "CQ",
	"cr":                                     "CR",
	"croatia":                                "HR",
	"cs":                                     "RS",
	"cu":                                     "CU",
	"cuba":                                   "CU",
	"curaçao":                                "CW",
	"cv":                                     "CV",
	"cw":                                     "CW",
	"cx":                                     "CX",
	"cy":                                     "CY",
	"cyprus":                                 "CY",
	"cz":                                     "CZ",
	"czech republic":                         "CZ",
	"czechia":                                "CZ",
	"dd":                                     "DE",
	"de":                                     "DE",
	"denmark":                                "DK",
	"dg":                                     "DG",
	"diego garcia":                           "DG",
	"dj":                                     "DJ",
	"djibouti":                               "DJ",
	"dk":                                     "DK",
	"dm":                                     "DM",
	"do":                                     "DO",
	"dominica":                               "DM",
	"dominican republic":                     "DO",
	"dy":                                     "BJ",
	"dz":                                     "DZ",
	"ea":                                     "EA",
	"ec":                                     "EC",
	"ecuador":                                "EC",
	"ee":                                     "EE",
	"eg":                                     "EG",
	"egypt":                                  "EG",
	"eh":                                     "EH",
	"el salvador":                            "SV",
	"equatorial guinea":                      "GQ",
	"er":                                     "ER",
	"eritrea":                                "ER",
	"es":                                     "ES",
	"estonia":                                "EE",
	"eswatini":                               "SZ",
	"et":                                     "ET",
	"ethiopia":                               "ET",
	"eu":                                     "EU",
	"european union":                         "EU",
	"eurozone":                               "EZ",
	"ez":                                     "EZ",
	"falkland islands":                       "FK",
	"faroe islands":                          "FO",
	"fi":                                     "FI",
	"fiji":                                   "FJ",
	"finland":                                "FI",
	"fj":                                     "FJ",
	"fk":                                     "FK",
	"fm":                                     "FM",
	"fo":                                     "FO",
	"fr":                                     "FR",
	"france":                                 "FR",
	"french guiana":                          "GF",
	"french polynesia":                       "PF",
	"french southern territories":            "TF",
	"fx":                                     "FR",
	"ga":                                     "GA",
	"gabon":                                  "GA",
	"gambia":                                 "GM",
	"gb":                                     "GB",
	"gd":                                     "GD",
	"ge":                                     "GE",
	"georgia":                                "GE",
	"germany":                                "DE",
	"gf":                                     "GF",
	"gg":                                     "GG",
	"gh":                                     "GH",
	"ghana":                                  "GH",
	"gi":                                     "GI",
	"gibraltar":                              "GI",
	"gl":                                     "GL",
	"gm":                                     "GM",
	"gn":                                     "GN",
	"gp":                                     "GP",
	"gq":                                     "GQ",
	"gr":                                     "GR",
	"great britain":                          "GB",
	"greece":                                 "GR",
	"greenland":                              "GL",
	"grenada":                                "GD",
	"gs":                                     "GS",
	"gt":                                     "GT",
	"gu":                                     "GU",
	"guadeloupe":                             "GP",
	"guam":                                   "GU",
	"guatemala":                              "GT",
	"guernsey":                               "GG",
	"guinea":                                 "GN",
	"guinea-bissau":                          "GW",
	"guyana":                                 "GY",
	"gw":                                     "GW",
	"gy":                                     "GY",
	"haiti":                                  "HT",
	"heard & mcdonald islands":               "HM",
	"hk":                                     "HK",
	"hm":                                     "HM",
	"hn":                                     "HN",
	"honduras":                               "HN",
	"hong kong sar china":                    "HK",
	"hr":                                     "HR",
	"ht":                                     "HT",
	"hu":                                     "HU",
	"hungary":                                "HU",
	"hv":                                     "BF",
	"ic":                                     "IC",
	"iceland":                                "IS",
	"id":                                     "ID",
	"ie":                                     "IE",
	"il":                                     "IL",
	"im":                                     "IM",
	"in":                                     "IN",
	"india":                                  "IN",
	"indonesia":                              "ID",
	"io":                                     "IO",
	"iq":                                     "IQ",
	"ir":                                     "IR",
	"iran":                                   "IR",
	"iran, islamic republic of":              "IR",
	"iraq":                                   "IQ",
	"ireland":                                "IE",
	"is":                                     "IS",
	"isle of man":                            "IM",
	"israel":                                 "IL",
	"it":                                     "IT",
	"italy":                                  "IT",
	"jamaica":                                "JM",
	"japan":                                  "JP",
	"je":                                     "JE",
	"jersey":                                 "JE",
	"jm":                                     "JM",
	"jo":                                     "JO",
	"jordan":                                 "JO",
	"jp":                                     "JP",
	"kazakhstan":                             "KZ",
	"ke":                                     "KE",
	"kenya":                                  "KE",
	"kg":                                     "KG",
	"kh":                                     "KH",
	"ki":                                     "KI",
	"kiribati":                               "KI",
	"km":                                     "KM",
	"kn":                                     "KN",
	"korea, republic of":                     "KR",
	"kosovo":                                 "XK",
	"kp":                                     "KP",
	"kr":                                     "KR",
	"kuwait":                                 "KW",
	"kw":                                     "KW",
	"ky":                                     "KY",
	"kyrgyzstan":                             "KG",
	"kz":                                     "KZ",
	"la":                                     "LA",
	"laos":                                   "LA",
	"latvia":                                 "LV",
	"lb":                                     "LB",
	"lc":                                     "LC",
	"lebanon":                                "LB",
	"lesotho":                                "LS",
	"li":                                     "LI",
	"liberia":                                "LR",
	"libya":                                  "LY",
	"liechtenstein":                          "LI",
	"lithuania":                              "LT",
	"lk":                                     "LK",
	"lr":                                     "LR",
	"ls":                                     "LS",
	"lt":                                     "LT",
	"lu":                                     "LU",
	"luxembourg":                             "LU",
	"lv":                                     "LV",
	"ly":                                     "LY",
	"ma":                                     "MA",
	"macao sar china":                        "MO",
	"madagascar":                             "MG",
	"malawi":                                 "MW",
	"malaysia":                               "MY",
	"maldives":                               "MV",
	"mali":                                   "ML",
	"malta":                                  "MT",
	"marshall islands":                       "MH",
	"martinique":                             "MQ",
	"mauritania":                             "MR",
	"mauritius":                              "MU",
	"mayotte":                                "YT",
	"mc":                                     "MC",
	"md":                                     "MD",
	"me":                                     "ME",
	"mexico":                                 "MX",
	"mf":                                     "MF",
	"mg":                                     "MG",
	"mh":                                     "MH",
	"micronesia":                             "FM",
	"mk":                                     "MK",
	"ml":                                     "ML",
	"mm":                                     "MM",
	"mn":                                     "MN",
	"mo":                                     "MO",
	"moldova":                                "MD",
	"monaco":                                 "MC",
	"mongolia":                               "MN",
	"montenegro":                             "ME",
	"montserrat":                             "MS",
	"morocco":                                "MA",
	"mozambique":                             "MZ",
	"mp":                                     "MP",
	"mq":                                     "MQ",
	"mr":                                     "MR",
	"ms":                                     "MS",
	"mt":                                     "MT",
	"mu":                                     "MU",
	"mv":                                     "MV",
	"mw":                                     "MW",
	"mx":                                     "MX",
	"my":                                     "MY",
	"myanmar (burma)":                        "MM",
	"mz":                                     "MZ",
	"na":                                     "NA",
	"namibia":                                "NA",
	"nauru":                                  "NR",
	"nc":                                     "NC",
	"ne":                                     "NE",
	"nepal":                                  "NP",
	"netherlands":                            "NL",
	"new caledonia":                          "NC",
	"new zealand":                            "NZ",
	"nf":                                     "NF",
	"ng":                                     "NG",
	"nh":                                     "VU",
	"ni":                                     "NI",
	"nicaragua":                              "NI",
	"niger":                                  "NE",
	"nigeria":                                "NG",
	"niue":                                   "NU",
	"nl":                                     "NL",
	"no":                                     "NO",
	"norfolk island":                         "NF",
	"north korea":                            "KP",
	"north macedonia":                        "MK",
	"northern mariana islands":               "MP",
	"norway":                                 "NO",
	"np":                                     "NP",
	"nr":                                     "NR",
	"nu":                                     "NU",
	"nz":                                     "NZ",
	"om":                                     "OM",
	"oman":                                   "OM",
	"outlying oceania":                       "QO",
	"pa":                                     "PA",
	"pakistan":                               "PK",
	"palau":                                  "PW",
	"palestinian territories":                "PS",
	"panama":                                 "PA",
	"papua new guinea":                       "PG",
	"paraguay":                               "PY",
	"pe":                                     "PE",
	"peru":                                   "PE",
	"pf":                                     "PF",
	"pg":                                     "PG",
	"ph":                                     "PH",
	"philippines":                            "PH",
	"pitcairn islands":                       "PN",
	"pk":                                     "PK",
	"pl":                                     "PL",
	"pm":                                     "PM",
	"pn":                                     "PN",
	"poland":                                 "PL",
	"portugal":                               "PT",
	"pr":                                     "PR",
	"ps":                                     "PS",
	"pseudo-accents":                         "XA",
	"pseudo-bidi":                            "XB",
	"pt":                                     "PT",
	"puerto rico":                            "PR",
	"pw":                                     "PW",
	"py":                                     "PY",
	"qa":                                     "QA",
	"qatar":                                  "QA",
	"qo":                                     "QO",
	"re":                                     "RE",
	"republic of korea":                      "KR",
	"réunion":                                "RE",
	"rh":                                     "ZW",
	"ro":                                     "RO",
	"romania":                                "RO",
	"rs":                                     "RS",
	"ru":                                     "RU",
	"russia":                                 "RU",
	"russian federation":                     "RU",
	"rw":                                     "RW",
	"rwanda":                                 "RW",
	"sa":                                     "SA",
	"samoa":                                  "WS",
	"san marino":                             "SM",
	"são tomé & príncipe":                    "ST",
	"sark":                                   "CQ",
	"saudi arabia":                           "SA",
	"sb":                                     "SB",
	"sc":                                     "SC",
	"sd":                                     "SD",
	"se":                                     "SE",
	"senegal":                                "SN",
	"serbia":                                 "RS",
	"seychelles":                             "SC",
	"sg":                                     "SG",
	"sh":                                     "SH",
	"si":                                     "SI",
	"sierra leone":                           "SL",
	"singapore":                              "SG",
	"sint maarten":                           "SX",
	"sj":                                     "SJ",
	"sk":                                     "SK",
	"sl":                                     "SL",
	"slovakia":                               "SK",
	"slovenia":                               "SI",
	"sm":                                     "SM",
	"sn":                                     "SN",
	"so":                                     "SO",
	"solomon islands":                        "SB",
	"somalia":                                "SO",
	"south africa":                           "ZA",
	"south georgia & south sandwich islands": "GS",
	"south korea":                            "KR",
	"south sudan":                            "SS",
	"spain":                                  "ES",
	"sr":                                     "SR",
	"sri lanka":                              "LK",
	"ss":                                     "SS",
	"st":                                     "ST",
	"st. barthélemy":                         "BL",
	"st. helena":                             "SH",
	"st. kitts & nevis":                      "KN",
	"st. lucia":                              "LC",
	"st. martin":                             "MF",
	"st. pierre & miquelon":                  "PM",
	"st. vincent & grenadines":               "VC",
	"su":                                     "RU",
	"sudan":                                  "SD",
	"suriname":                               "SR",
	"sv":                                     "SV",
	"svalbard & jan mayen":                   "SJ",
	"sweden":                                 "SE",
	"switzerland":                            "CH",
	"sx":                                     "SX",
	"sy":                                     "SY",
	"syria":                                  "SY",
	"sz":                                     "SZ",
	"ta":                                     "TA",
	"taiwan":                                 "TW",
	"taiwan, province of china":              "TW",
	"tajikistan":                             "TJ",
	"tanzania":                               "TZ",
	"tc":                                     "TC",
	"td":                                     "TD",
	"tf":                                     "TF",
	"tg":                                     "TG",
	"th":                                     "TH",
	"thailand":                               "TH",
	"the united kingdom of great britain and northern ireland": "GB",
	"the united states of america":                             "US",
	"timor-leste":                                              "TL",
	"tj":                                                       "TJ",
	"tk":                                                       "TK",
	"tl":                                                       "TL",
	"tm":                                                       "TM",
	"tn":                                                       "TN",
	"to":                                                       "TO",
	"togo":                                                     "TG",
	"tokelau":                                                  "TK",
	"tonga":                                                    "TO",
	"tp":                                                       "TL",
	"tr":                                                       "TR",
	"trinidad & tobago":                                        "TT",
	"tristan da cunha":                                         "TA",
	"tt":                                                       "TT",
	"tunisia":                                                  "TN",
	"türkiye":                                                  "TR",
	"turkmenistan":                                             "TM",
	"turks & caicos islands":                                   "TC",
	"tuvalu":                                                   "TV",
	"tv":                                                       "TV",
	"tw":                                                       "TW",
	"tz":                                                       "TZ",
	"u.s. outlying islands":                                    "UM",
	"u.s. virgin islands":                                      "VI",
	"ua":                                                       "UA",
	"ug":                                                       "UG",
	"uganda":                                                   "UG",
	"uk":                                                       "GB",
	"ukraine":                                                  "UA",
	"um":                                                       "UM",
	"un":                                                       "UN",
	"united arab emirates":                                     "AE",
	"united kingdom":                                           "GB",
	"united kingdom of great britain and northern ireland": "GB",
	"united nations":                    "UN",
	"united states":                     "US",
	"united states of america":          "US",
	"uruguay":                           "UY",
	"us":                                "US",
	"usa":                               "US",
	"uy":                                "UY",
	"uz":                                "UZ",
	"uzbekistan":                        "UZ",
	"va":                                "VA",
	"vanuatu":                           "VU",
	"vatican city":                      "VA",
	"vc":                                "VC",
	"vd":                                "VN",
	"ve":                                "VE",
	"venezuela":                         "VE",
	"venezuela, bolivarian republic of": "VE",
	"vg":                                "VG",
	"vi":                                "VI",
	"viet nam":                          "VN",
	"vietnam":                           "VN",
	"vn":                                "VN",
	"vu":                                "VU",
	"wallis & futuna":                   "WF",
	"western sahara":                    "EH",
	"wf":                                "WF",
	"ws":                                "WS",
	"xa":                                "XA",
	"xb":                                "XB",
	"xk":                                "XK",
	"yd":                                "YE",
	"ye":                                "YE",
	"yemen":                             "YE",
	"yt":                                "YT",
	"yu":                                "RS",
	"za":                                "ZA",
	"zambia":                            "ZM",
	"zimbabwe":                          "ZW",
	"zm":                                "ZM",
	"zr":                                "CD",
	"zw":                                "ZW",
}

func countryFlag(country, code string) string {
	region := countryCodes[strings.ToLower(strings.TrimSpace(code))]
	if region == "" {
		region = countryCodes[strings.TrimPrefix(strings.ToLower(strings.TrimSpace(country)), "the ")]
	}
	if len(region) != 2 {
		return "🌍"
	}
	return string([]rune{0x1F1E6 + rune(region[0]-'A'), 0x1F1E6 + rune(region[1]-'A')})
}
